
export const SET_ROLE = 'SET_ROLE';


export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const CREATE_NEW_COURSE = 'CREATE_NEW_COURSE';
export const SELECT_COURSE = 'SELECT_COURSE';
export const REMOVE_SELECTED_COURSE = 'REMOVE_SELECTED_COURSE';


export const FILTER_COURSES = 'FILTER_COURSES';
export const FILTER_COURSES_BY_DIFFICULTY = 'FILTER_COURSES_BY_DIFFICULTY';
export const FILTER_COURSES_BY_PRICE = 'FILTER_COURSES_BY_PRICE';
export const FILTER_COURSES_BY_TIME = 'FILTER_COURSES_BY_TIME';
export const COURSES_ERROR = 'COURSES_ERROR';


export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";

