export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const FILTER_COURSES = 'FILTER_COURSES';
export const FILTER_COURSES_BY_DIFFICULTY = 'FILTER_COURSES_BY_DIFFICULTY';
export const FILTER_COURSES_BY_PRICE = 'FILTER_COURSES_BY_PRICE';
export const FILTER_COURSES_BY_TIME = 'FILTER_COURSES_BY_TIME';

